import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'de' | 'fr' | 'zh' | 'ko' | 'ja' | 'ru' | 'tr' | 'it' | 'da' | 'ro' | 'nl' | 'uk' | 'pl' | 'de-DE';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    home: 'Home',
    dashboard: 'Dashboard',
    trading: 'Trading',
    kyc: 'KYC Verification',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    swap: 'Coin Swapper',
    admin: 'Admin Panel',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    totalAssets: 'Total Assets',
    recentTransactions: 'Recent Transactions',
    trade: 'Trade',
    submit: 'Submit',
    cancel: 'Cancel',
    approve: 'Approve',
    reject: 'Reject',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    features: 'Features',
    whyChoose: 'Why Choose Bitget Trading',
    howItWorks: 'How It Works',
    faq: 'FAQ',
    getStarted: 'Get Started',
    welcome: 'Welcome to Bitget Trading',
    tagline: 'The Future of Crypto Trading',
  },
  es: {
    home: 'Inicio',
    dashboard: 'Panel',
    trading: 'Comercio',
    kyc: 'Verificación KYC',
    deposit: 'Depósito',
    withdraw: 'Retirar',
    swap: 'Intercambio',
    admin: 'Panel de Administración',
    login: 'Iniciar Sesión',
    signup: 'Registrarse',
    logout: 'Cerrar Sesión',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    totalAssets: 'Activos Totales',
    recentTransactions: 'Transacciones Recientes',
    trade: 'Comerciar',
    submit: 'Enviar',
    cancel: 'Cancelar',
    approve: 'Aprobar',
    reject: 'Rechazar',
    pending: 'Pendiente',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    features: 'Características',
    whyChoose: 'Por Qué Elegir Bitget Trading',
    howItWorks: 'Cómo Funciona',
    faq: 'Preguntas Frecuentes',
    getStarted: 'Comenzar',
    welcome: 'Bienvenido a Bitget Trading',
    tagline: 'El Futuro del Comercio de Criptomonedas',
  },
  de: {
    home: 'Startseite',
    dashboard: 'Dashboard',
    trading: 'Handel',
    kyc: 'KYC-Verifizierung',
    deposit: 'Einzahlung',
    withdraw: 'Abheben',
    swap: 'Tausch',
    admin: 'Admin-Panel',
    login: 'Anmelden',
    signup: 'Registrieren',
    logout: 'Abmelden',
    email: 'E-Mail',
    password: 'Passwort',
    totalAssets: 'Gesamtvermögen',
    recentTransactions: 'Letzte Transaktionen',
    trade: 'Handeln',
    submit: 'Einreichen',
    cancel: 'Abbrechen',
    approve: 'Genehmigen',
    reject: 'Ablehnen',
    pending: 'Ausstehend',
    approved: 'Genehmigt',
    rejected: 'Abgelehnt',
    features: 'Funktionen',
    whyChoose: 'Warum Bitget Trading',
    howItWorks: 'Wie Es Funktioniert',
    faq: 'FAQ',
    getStarted: 'Loslegen',
    welcome: 'Willkommen bei Bitget Trading',
    tagline: 'Die Zukunft des Krypto-Handels',
  },
  fr: {
    home: 'Accueil',
    dashboard: 'Tableau de Bord',
    trading: 'Trading',
    kyc: 'Vérification KYC',
    deposit: 'Dépôt',
    withdraw: 'Retrait',
    swap: 'Échange',
    admin: 'Panneau Admin',
    login: 'Connexion',
    signup: 'Inscription',
    logout: 'Déconnexion',
    email: 'Email',
    password: 'Mot de Passe',
    totalAssets: 'Actifs Totaux',
    recentTransactions: 'Transactions Récentes',
    trade: 'Trader',
    submit: 'Soumettre',
    cancel: 'Annuler',
    approve: 'Approuver',
    reject: 'Rejeter',
    pending: 'En Attente',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    features: 'Fonctionnalités',
    whyChoose: 'Pourquoi Choisir Bitget Trading',
    howItWorks: 'Comment Ça Marche',
    faq: 'FAQ',
    getStarted: 'Commencer',
    welcome: 'Bienvenue sur Bitget Trading',
    tagline: 'L\'Avenir du Trading Crypto',
  },
  zh: {
    home: '首页',
    dashboard: '仪表板',
    trading: '交易',
    kyc: 'KYC验证',
    deposit: '存款',
    withdraw: '提款',
    swap: '兑换',
    admin: '管理面板',
    login: '登录',
    signup: '注册',
    logout: '登出',
    email: '电子邮件',
    password: '密码',
    totalAssets: '总资产',
    recentTransactions: '最近交易',
    trade: '交易',
    submit: '提交',
    cancel: '取消',
    approve: '批准',
    reject: '拒绝',
    pending: '待处理',
    approved: '已批准',
    rejected: '已拒绝',
    features: '功能',
    whyChoose: '为什么选择Bitget Trading',
    howItWorks: '如何运作',
    faq: '常见问题',
    getStarted: '开始',
    welcome: '欢迎来到Bitget Trading',
    tagline: '加密货币交易的未来',
  },
  ko: {
    home: '홈',
    dashboard: '대시보드',
    trading: '거래',
    kyc: 'KYC 인증',
    deposit: '입금',
    withdraw: '출금',
    swap: '스왑',
    admin: '관리자 패널',
    login: '로그인',
    signup: '가입',
    logout: '로그아웃',
    email: '이메일',
    password: '비밀번호',
    totalAssets: '총 자산',
    recentTransactions: '최근 거래',
    trade: '거래',
    submit: '제출',
    cancel: '취소',
    approve: '승인',
    reject: '거부',
    pending: '대기중',
    approved: '승인됨',
    rejected: '거부됨',
    features: '기능',
    whyChoose: 'Bitget Trading을 선택하는 이유',
    howItWorks: '작동 방식',
    faq: 'FAQ',
    getStarted: '시작하기',
    welcome: 'Bitget Trading에 오신 것을 환영합니다',
    tagline: '암호화폐 거래의 미래',
  },
  ja: {
    home: 'ホーム',
    dashboard: 'ダッシュボード',
    trading: '取引',
    kyc: 'KYC認証',
    deposit: '入金',
    withdraw: '出金',
    swap: 'スワップ',
    admin: '管理パネル',
    login: 'ログイン',
    signup: '登録',
    logout: 'ログアウト',
    email: 'メール',
    password: 'パスワード',
    totalAssets: '総資産',
    recentTransactions: '最近の取引',
    trade: '取引',
    submit: '送信',
    cancel: 'キャンセル',
    approve: '承認',
    reject: '拒否',
    pending: '保留中',
    approved: '承認済み',
    rejected: '拒否済み',
    features: '機能',
    whyChoose: 'Bitget Tradingを選ぶ理由',
    howItWorks: '仕組み',
    faq: 'よくある質問',
    getStarted: '始める',
    welcome: 'Bitget Tradingへようこそ',
    tagline: '暗号通貨取引の未来',
  },
  ru: {
    home: 'Главная',
    dashboard: 'Панель',
    trading: 'Торговля',
    kyc: 'KYC Верификация',
    deposit: 'Депозит',
    withdraw: 'Вывод',
    swap: 'Обмен',
    admin: 'Админ Панель',
    login: 'Войти',
    signup: 'Регистрация',
    logout: 'Выйти',
    email: 'Эл. почта',
    password: 'Пароль',
    totalAssets: 'Всего Активов',
    recentTransactions: 'Последние Транзакции',
    trade: 'Торговать',
    submit: 'Отправить',
    cancel: 'Отмена',
    approve: 'Одобрить',
    reject: 'Отклонить',
    pending: 'Ожидание',
    approved: 'Одобрено',
    rejected: 'Отклонено',
    features: 'Возможности',
    whyChoose: 'Почему Bitget Trading',
    howItWorks: 'Как Это Работает',
    faq: 'FAQ',
    getStarted: 'Начать',
    welcome: 'Добро пожаловать в Bitget Trading',
    tagline: 'Будущее Крипто Торговли',
  },
  tr: {
    home: 'Ana Sayfa',
    dashboard: 'Kontrol Paneli',
    trading: 'Ticaret',
    kyc: 'KYC Doğrulama',
    deposit: 'Para Yatırma',
    withdraw: 'Para Çekme',
    swap: 'Takas',
    admin: 'Yönetici Paneli',
    login: 'Giriş Yap',
    signup: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    email: 'E-posta',
    password: 'Şifre',
    totalAssets: 'Toplam Varlıklar',
    recentTransactions: 'Son İşlemler',
    trade: 'Ticaret Yap',
    submit: 'Gönder',
    cancel: 'İptal',
    approve: 'Onayla',
    reject: 'Reddet',
    pending: 'Beklemede',
    approved: 'Onaylandı',
    rejected: 'Reddedildi',
    features: 'Özellikler',
    whyChoose: 'Neden Bitget Trading',
    howItWorks: 'Nasıl Çalışır',
    faq: 'SSS',
    getStarted: 'Başla',
    welcome: 'Bitget Trading\'e Hoş Geldiniz',
    tagline: 'Kripto Ticaretin Geleceği',
  },
  it: {
    home: 'Home',
    dashboard: 'Pannello',
    trading: 'Trading',
    kyc: 'Verifica KYC',
    deposit: 'Deposito',
    withdraw: 'Prelievo',
    swap: 'Scambio',
    admin: 'Pannello Admin',
    login: 'Accedi',
    signup: 'Registrati',
    logout: 'Esci',
    email: 'Email',
    password: 'Password',
    totalAssets: 'Totale Asset',
    recentTransactions: 'Transazioni Recenti',
    trade: 'Commercia',
    submit: 'Invia',
    cancel: 'Annulla',
    approve: 'Approva',
    reject: 'Rifiuta',
    pending: 'In Attesa',
    approved: 'Approvato',
    rejected: 'Rifiutato',
    features: 'Caratteristiche',
    whyChoose: 'Perché Scegliere Bitget Trading',
    howItWorks: 'Come Funziona',
    faq: 'FAQ',
    getStarted: 'Inizia',
    welcome: 'Benvenuto su Bitget Trading',
    tagline: 'Il Futuro del Trading Crypto',
  },
  da: {
    home: 'Hjem',
    dashboard: 'Dashboard',
    trading: 'Handel',
    kyc: 'KYC Verifikation',
    deposit: 'Indbetaling',
    withdraw: 'Udbetaling',
    swap: 'Bytte',
    admin: 'Admin Panel',
    login: 'Log Ind',
    signup: 'Tilmeld',
    logout: 'Log Ud',
    email: 'Email',
    password: 'Adgangskode',
    totalAssets: 'Samlede Aktiver',
    recentTransactions: 'Seneste Transaktioner',
    trade: 'Handel',
    submit: 'Indsend',
    cancel: 'Annuller',
    approve: 'Godkend',
    reject: 'Afvis',
    pending: 'Afventende',
    approved: 'Godkendt',
    rejected: 'Afvist',
    features: 'Funktioner',
    whyChoose: 'Hvorfor Vælge Bitget Trading',
    howItWorks: 'Sådan Fungerer Det',
    faq: 'FAQ',
    getStarted: 'Kom I Gang',
    welcome: 'Velkommen til Bitget Trading',
    tagline: 'Fremtiden for Krypto Handel',
  },
  ro: {
    home: 'Acasă',
    dashboard: 'Panou',
    trading: 'Tranzacționare',
    kyc: 'Verificare KYC',
    deposit: 'Depozit',
    withdraw: 'Retragere',
    swap: 'Schimb',
    admin: 'Panou Admin',
    login: 'Autentificare',
    signup: 'Înregistrare',
    logout: 'Deconectare',
    email: 'Email',
    password: 'Parolă',
    totalAssets: 'Active Totale',
    recentTransactions: 'Tranzacții Recente',
    trade: 'Tranzacționează',
    submit: 'Trimite',
    cancel: 'Anulează',
    approve: 'Aprobă',
    reject: 'Respinge',
    pending: 'În Așteptare',
    approved: 'Aprobat',
    rejected: 'Respins',
    features: 'Caracteristici',
    whyChoose: 'De Ce Bitget Trading',
    howItWorks: 'Cum Funcționează',
    faq: 'Întrebări Frecvente',
    getStarted: 'Începe',
    welcome: 'Bun venit la Bitget Trading',
    tagline: 'Viitorul Tranzacționării Crypto',
  },
  nl: {
    home: 'Home',
    dashboard: 'Dashboard',
    trading: 'Handelen',
    kyc: 'KYC Verificatie',
    deposit: 'Storting',
    withdraw: 'Opname',
    swap: 'Ruilen',
    admin: 'Admin Paneel',
    login: 'Inloggen',
    signup: 'Aanmelden',
    logout: 'Uitloggen',
    email: 'Email',
    password: 'Wachtwoord',
    totalAssets: 'Totale Activa',
    recentTransactions: 'Recente Transacties',
    trade: 'Handelen',
    submit: 'Indienen',
    cancel: 'Annuleren',
    approve: 'Goedkeuren',
    reject: 'Afwijzen',
    pending: 'In Behandeling',
    approved: 'Goedgekeurd',
    rejected: 'Afgewezen',
    features: 'Kenmerken',
    whyChoose: 'Waarom Bitget Trading',
    howItWorks: 'Hoe Het Werkt',
    faq: 'FAQ',
    getStarted: 'Aan De Slag',
    welcome: 'Welkom bij Bitget Trading',
    tagline: 'De Toekomst van Crypto Handelen',
  },
  uk: {
    home: 'Головна',
    dashboard: 'Панель',
    trading: 'Торгівля',
    kyc: 'KYC Верифікація',
    deposit: 'Депозит',
    withdraw: 'Виведення',
    swap: 'Обмін',
    admin: 'Адмін Панель',
    login: 'Увійти',
    signup: 'Реєстрація',
    logout: 'Вийти',
    email: 'Електронна Пошта',
    password: 'Пароль',
    totalAssets: 'Загальні Активи',
    recentTransactions: 'Останні Транзакції',
    trade: 'Торгувати',
    submit: 'Надіслати',
    cancel: 'Скасувати',
    approve: 'Схвалити',
    reject: 'Відхилити',
    pending: 'Очікування',
    approved: 'Схвалено',
    rejected: 'Відхилено',
    features: 'Можливості',
    whyChoose: 'Чому Bitget Trading',
    howItWorks: 'Як Це Працює',
    faq: 'Питання',
    getStarted: 'Почати',
    welcome: 'Ласкаво просимо до Bitget Trading',
    tagline: 'Майбутнє Крипто Торгівлі',
  },
  pl: {
    home: 'Strona Główna',
    dashboard: 'Panel',
    trading: 'Handel',
    kyc: 'Weryfikacja KYC',
    deposit: 'Wpłata',
    withdraw: 'Wypłata',
    swap: 'Wymiana',
    admin: 'Panel Admina',
    login: 'Zaloguj',
    signup: 'Zarejestruj',
    logout: 'Wyloguj',
    email: 'Email',
    password: 'Hasło',
    totalAssets: 'Łączne Aktywa',
    recentTransactions: 'Ostatnie Transakcje',
    trade: 'Handel',
    submit: 'Wyślij',
    cancel: 'Anuluj',
    approve: 'Zatwierdź',
    reject: 'Odrzuć',
    pending: 'Oczekujące',
    approved: 'Zatwierdzone',
    rejected: 'Odrzucone',
    features: 'Funkcje',
    whyChoose: 'Dlaczego Bitget Trading',
    howItWorks: 'Jak To Działa',
    faq: 'FAQ',
    getStarted: 'Rozpocznij',
    welcome: 'Witamy w Bitget Trading',
    tagline: 'Przyszłość Handlu Krypto',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export const languageOptions = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'de', name: 'Deutsch' },
  { code: 'fr', name: 'Français' },
  { code: 'zh', name: '中文' },
  { code: 'ko', name: '한국어' },
  { code: 'ja', name: '日本語' },
  { code: 'ru', name: 'Русский' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'it', name: 'Italiano' },
  { code: 'da', name: 'Dansk' },
  { code: 'ro', name: 'Română' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'uk', name: 'Українська' },
  { code: 'pl', name: 'Polski' },
];
